Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KenkoApp.Data;
using KenkoApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace KenkoApp.Controllers
{
    [Authorize]
    public class AppointmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CustomIdentityUser> _userManager;

        public AppointmentsController(ApplicationDbContext context, UserManager<CustomIdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();

            List<Appointment> model = _context
                .Appointment
                .Where(x => x.CustomIdentityUser.Id == currentUser.Id)
                .ToList();
            return View(model);
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .FirstOrDefaultAsync(m => m.AppointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateTime,AppointmentID,ReasonForVisit")] Appointment appointment, List<IFormFile> fileInputData, string UserID)
        {

            var user = await _userManager.GetUserAsync(User);
            appointment.CustomIdentityUser = user;

            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
          
            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DateTime,AppointmentID,ReasonForVisit")] Appointment appointment)
        {
            if (id != appointment.AppointmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.AppointmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .FirstOrDefaultAsync(m => m.AppointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appointment = await _context.Appointment.FindAsync(id);
            _context.Appointment.Remove(appointment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
            return _context.Appointment.Any(e => e.AppointmentID == id);
        }
    }
}

Controllers/HealthRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KenkoApp.Data;
using KenkoApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace KenkoApp.Controllers
{
    [Authorize]
    public class HealthRecordsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CustomIdentityUser> _userManager;

        public HealthRecordsController(ApplicationDbContext context, UserManager<CustomIdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: HealthRecords
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();
           
            List<HealthRecord> model = _context
                .HealthRecords
                .Where(x => x.CustomIdentityUser.Id == currentUser.Id)
                .ToList();
            return View(model); 

            //return View(currentUser);
            //if the current user id matches the CustomerUserID associated with the healthrecord, show those records.
            //code from Michael
        }

        // GET: HealthRecords/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var healthRecord = await _context.HealthRecords
                .FirstOrDefaultAsync(m => m.HealthRecordID == id);

            if (healthRecord == null)
            {
                return NotFound();
            }

            return View(healthRecord);
        }

        public async Task<IActionResult> Display(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var record = await _context.HealthRecords
                .FirstOrDefaultAsync(m => m.HealthRecordID == id);
            if (record == null)
            {
                return NotFound();
            }

            return File(record.RecordData, record.FileType);
        }

        // GET: HealthRecords/Create
        public IActionResult Upload()
        {
            return View();
        }

        // POST: HealthRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload([Bind("HealthRecordID,Title,RecordData,FileType,RecordNotes,")] HealthRecord healthRecord,List<IFormFile> fileInputData, string UserID) //removed CustomerUserId from Bind
        {
            //var CurrentUser = _context
            //   .CustomIdentityUsers
            //   .SingleOrDefault(x => x.Id == UserID);

            //healthRecord.CustomIdentityUser = CurrentUser;

            var user = await _userManager.GetUserAsync(User);
            healthRecord.CustomIdentityUser = user;



            //ViewBag.id = _userManager.GetUserId(HttpContext.User);  what I had before
            //var currentUser = await _userManager.GetUserAsync(User);
            //healthRecord.CustomIdentityUser = currentUser;


            if (ModelState.IsValid)
            {
                if (fileInputData.Count > 1)
                {
                    ModelState.AddModelError("RecordData", "Please upload only one file.");
                }
                var formFile = fileInputData[0]; //get first file
                var readStream = formFile.OpenReadStream(); //get stream of uploaded data
                healthRecord.RecordData = new byte[formFile.Length]; // create array on database photo object big enough to hold
                readStream.Read(healthRecord.RecordData, 0, (int)formFile.Length);//load data from stream into database phot object
                healthRecord.FileType = formFile.ContentType; //set database photo mime type based on type of file; png, jpg, etc.
                _context.Add(healthRecord); //add database photo object database gateway DbContext
                await _context.SaveChangesAsync(); //save changes to create insert statement
                return RedirectToAction(nameof(Index));
            }
            return View(healthRecord);
        }

        // GET: HealthRecords/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var healthRecord = await _context.HealthRecords.FindAsync(id);
            if (healthRecord == null)
            {
                return NotFound();
            }
            return View(healthRecord);
        }

        // POST: HealthRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HealthRecordID,Title,RecordData,MimeType")] HealthRecord healthRecord)
        {
            if (id != healthRecord.HealthRecordID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(healthRecord);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HealthRecordExists(healthRecord.HealthRecordID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(healthRecord);
        }

        // GET: HealthRecords/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var healthRecord = await _context.HealthRecords
                .FirstOrDefaultAsync(m => m.HealthRecordID == id);
            if (healthRecord == null)
            {
                return NotFound();
            }

            return View(healthRecord);
        }

        // POST: HealthRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var healthRecord = await _context.HealthRecords.FindAsync(id);
            _context.HealthRecords.Remove(healthRecord);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HealthRecordExists(int id)
        {
            return _context.HealthRecords.Any(e => e.HealthRecordID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@inject SignInManager<CustomIdentityUser> signIngManager;
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KenkoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @using Microsoft.AspNetCore.Identity
    @inject SignInManager<CustomIdentityUser> SignInManager
  
    @*<script>
        $(document).ready(function ($) {
            var url = window.location.href;
            var activePage = url;
            $('.irp-menu-item a').each(function () {
            var linkPage = this.href;

                if (activePage == linkPage) {
                    $(this).closest("li").addClass("active");
                    }
            });
        });
    </script>*@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light navbar-fixed bg-white border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img width="200" src="~/img/Kenko1_Kenko_logo_full.png" />
                </a>


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CustomIdentityUsers" asp-action="Details">Patient Info</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="HealthRecords" asp-action="Index">Records</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                            </li>
                            <li class="nav-item">
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <a class="nav-link" href="#aboutus">About Kenko</a>
                    <a class="nav-link" href="#overview">Health</a>
                    <a class="nav-link" href="#meettheteam">Meet the Team</a>
                    <a class="nav-link" href="#contact">Contact Us</a>

                }
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 content" style="padding-top:100px">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - KenkoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/navfunction.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @RenderSection("Scripts", required: false)

</body>
</html>